/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkPulseRouteImport } from './routes/work_.pulse'
import { Route as ExperienceLightmatterRouteImport } from './routes/experience_.lightmatter'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPulseRoute = WorkPulseRouteImport.update({
  id: '/work_/pulse',
  path: '/work/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceLightmatterRoute = ExperienceLightmatterRouteImport.update({
  id: '/experience_/lightmatter',
  path: '/experience/lightmatter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/work/pulse': typeof WorkPulseRoute
  '/experience/lightmatter': typeof ExperienceLightmatterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/work/pulse': typeof WorkPulseRoute
  '/experience/lightmatter': typeof ExperienceLightmatterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/work_/pulse': typeof WorkPulseRoute
  '/experience_/lightmatter': typeof ExperienceLightmatterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience' | '/thoughts' | '/work' | '/work/pulse' | '/experience/lightmatter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experience' | '/thoughts' | '/work' | '/work/pulse' | '/experience/lightmatter'
  id: '__root__' | '/' | '/experience' | '/thoughts' | '/work' | '/work_/pulse' | '/experience_/lightmatter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceRoute: typeof ExperienceRoute
  ThoughtsRoute: typeof ThoughtsRoute
  WorkRoute: typeof WorkRoute
  WorkPulseRoute: typeof WorkPulseRoute
  ExperienceLightmatterRoute: typeof ExperienceLightmatterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/pulse': {
      id: '/work_/pulse'
      path: '/work/pulse'
      fullPath: '/work/pulse'
      preLoaderRoute: typeof WorkPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience_/lightmatter': {
      id: '/experience_/lightmatter'
      path: '/experience/lightmatter'
      fullPath: '/experience/lightmatter'
      preLoaderRoute: typeof ExperienceLightmatterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceRoute: ExperienceRoute,
  ThoughtsRoute: ThoughtsRoute,
  WorkRoute: WorkRoute,
  WorkPulseRoute: WorkPulseRoute,
  ExperienceLightmatterRoute: ExperienceLightmatterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
