/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ExperienceLightmatterRouteImport } from './routes/experience_.lightmatter'
import { Route as ExperiencePmaRouteImport } from './routes/experience_.pma'
import { Route as ExperienceStemboxRouteImport } from './routes/experience_.stembox'
import { Route as ThoughtsEarlyWorksRouteImport } from './routes/thoughts_.early-works'
import { Route as ThoughtsLearningToTakeUpSpaceRouteImport } from './routes/thoughts_.learning-to-take-up-space'
import { Route as ThoughtsMagicInTheMundaneRouteImport } from './routes/thoughts_.magic-in-the-mundane'
import { Route as WorkFarmAppRouteImport } from './routes/work_.farm-app'
import { Route as WorkLidarRouteImport } from './routes/work_.lidar'
import { Route as WorkPulseRouteImport } from './routes/work_.pulse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceLightmatterRoute = ExperienceLightmatterRouteImport.update({
  id: '/experience_/lightmatter',
  path: '/experience/lightmatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencePmaRoute = ExperiencePmaRouteImport.update({
  id: '/experience_/pma',
  path: '/experience/pma',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceStemboxRoute = ExperienceStemboxRouteImport.update({
  id: '/experience_/stembox',
  path: '/experience/stembox',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsEarlyWorksRoute = ThoughtsEarlyWorksRouteImport.update({
  id: '/thoughts_/early-works',
  path: '/thoughts/early-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsLearningToTakeUpSpaceRoute =
  ThoughtsLearningToTakeUpSpaceRouteImport.update({
    id: '/thoughts_/learning-to-take-up-space',
    path: '/thoughts/learning-to-take-up-space',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThoughtsMagicInTheMundaneRoute =
  ThoughtsMagicInTheMundaneRouteImport.update({
    id: '/thoughts_/magic-in-the-mundane',
    path: '/thoughts/magic-in-the-mundane',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkFarmAppRoute = WorkFarmAppRouteImport.update({
  id: '/work_/farm-app',
  path: '/work/farm-app',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLidarRoute = WorkLidarRouteImport.update({
  id: '/work_/lidar',
  path: '/work/lidar',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPulseRoute = WorkPulseRouteImport.update({
  id: '/work_/pulse',
  path: '/work/pulse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/experience/lightmatter': typeof ExperienceLightmatterRoute
  '/experience/pma': typeof ExperiencePmaRoute
  '/experience/stembox': typeof ExperienceStemboxRoute
  '/thoughts/early-works': typeof ThoughtsEarlyWorksRoute
  '/thoughts/learning-to-take-up-space': typeof ThoughtsLearningToTakeUpSpaceRoute
  '/thoughts/magic-in-the-mundane': typeof ThoughtsMagicInTheMundaneRoute
  '/work/farm-app': typeof WorkFarmAppRoute
  '/work/lidar': typeof WorkLidarRoute
  '/work/pulse': typeof WorkPulseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/experience/lightmatter': typeof ExperienceLightmatterRoute
  '/experience/pma': typeof ExperiencePmaRoute
  '/experience/stembox': typeof ExperienceStemboxRoute
  '/thoughts/early-works': typeof ThoughtsEarlyWorksRoute
  '/thoughts/learning-to-take-up-space': typeof ThoughtsLearningToTakeUpSpaceRoute
  '/thoughts/magic-in-the-mundane': typeof ThoughtsMagicInTheMundaneRoute
  '/work/farm-app': typeof WorkFarmAppRoute
  '/work/lidar': typeof WorkLidarRoute
  '/work/pulse': typeof WorkPulseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/experience_/lightmatter': typeof ExperienceLightmatterRoute
  '/experience_/pma': typeof ExperiencePmaRoute
  '/experience_/stembox': typeof ExperienceStemboxRoute
  '/thoughts_/early-works': typeof ThoughtsEarlyWorksRoute
  '/thoughts_/learning-to-take-up-space': typeof ThoughtsLearningToTakeUpSpaceRoute
  '/thoughts_/magic-in-the-mundane': typeof ThoughtsMagicInTheMundaneRoute
  '/work_/farm-app': typeof WorkFarmAppRoute
  '/work_/lidar': typeof WorkLidarRoute
  '/work_/pulse': typeof WorkPulseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experience'
    | '/thoughts'
    | '/work'
    | '/experience/lightmatter'
    | '/experience/pma'
    | '/experience/stembox'
    | '/thoughts/early-works'
    | '/thoughts/learning-to-take-up-space'
    | '/thoughts/magic-in-the-mundane'
    | '/work/farm-app'
    | '/work/lidar'
    | '/work/pulse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experience'
    | '/thoughts'
    | '/work'
    | '/experience/lightmatter'
    | '/experience/pma'
    | '/experience/stembox'
    | '/thoughts/early-works'
    | '/thoughts/learning-to-take-up-space'
    | '/thoughts/magic-in-the-mundane'
    | '/work/farm-app'
    | '/work/lidar'
    | '/work/pulse'
  id:
    | '__root__'
    | '/'
    | '/experience'
    | '/thoughts'
    | '/work'
    | '/experience_/lightmatter'
    | '/experience_/pma'
    | '/experience_/stembox'
    | '/thoughts_/early-works'
    | '/thoughts_/learning-to-take-up-space'
    | '/thoughts_/magic-in-the-mundane'
    | '/work_/farm-app'
    | '/work_/lidar'
    | '/work_/pulse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceRoute: typeof ExperienceRoute
  ThoughtsRoute: typeof ThoughtsRoute
  WorkRoute: typeof WorkRoute
  ExperienceLightmatterRoute: typeof ExperienceLightmatterRoute
  ExperiencePmaRoute: typeof ExperiencePmaRoute
  ExperienceStemboxRoute: typeof ExperienceStemboxRoute
  ThoughtsEarlyWorksRoute: typeof ThoughtsEarlyWorksRoute
  ThoughtsLearningToTakeUpSpaceRoute: typeof ThoughtsLearningToTakeUpSpaceRoute
  ThoughtsMagicInTheMundaneRoute: typeof ThoughtsMagicInTheMundaneRoute
  WorkFarmAppRoute: typeof WorkFarmAppRoute
  WorkLidarRoute: typeof WorkLidarRoute
  WorkPulseRoute: typeof WorkPulseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience_/lightmatter': {
      id: '/experience_/lightmatter'
      path: '/experience/lightmatter'
      fullPath: '/experience/lightmatter'
      preLoaderRoute: typeof ExperienceLightmatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience_/pma': {
      id: '/experience_/pma'
      path: '/experience/pma'
      fullPath: '/experience/pma'
      preLoaderRoute: typeof ExperiencePmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience_/stembox': {
      id: '/experience_/stembox'
      path: '/experience/stembox'
      fullPath: '/experience/stembox'
      preLoaderRoute: typeof ExperienceStemboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/early-works': {
      id: '/thoughts_/early-works'
      path: '/thoughts/early-works'
      fullPath: '/thoughts/early-works'
      preLoaderRoute: typeof ThoughtsEarlyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/learning-to-take-up-space': {
      id: '/thoughts_/learning-to-take-up-space'
      path: '/thoughts/learning-to-take-up-space'
      fullPath: '/thoughts/learning-to-take-up-space'
      preLoaderRoute: typeof ThoughtsLearningToTakeUpSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/magic-in-the-mundane': {
      id: '/thoughts_/magic-in-the-mundane'
      path: '/thoughts/magic-in-the-mundane'
      fullPath: '/thoughts/magic-in-the-mundane'
      preLoaderRoute: typeof ThoughtsMagicInTheMundaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/farm-app': {
      id: '/work_/farm-app'
      path: '/work/farm-app'
      fullPath: '/work/farm-app'
      preLoaderRoute: typeof WorkFarmAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/lidar': {
      id: '/work_/lidar'
      path: '/work/lidar'
      fullPath: '/work/lidar'
      preLoaderRoute: typeof WorkLidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/pulse': {
      id: '/work_/pulse'
      path: '/work/pulse'
      fullPath: '/work/pulse'
      preLoaderRoute: typeof WorkPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceRoute: ExperienceRoute,
  ThoughtsRoute: ThoughtsRoute,
  WorkRoute: WorkRoute,
  ExperienceLightmatterRoute: ExperienceLightmatterRoute,
  ExperiencePmaRoute: ExperiencePmaRoute,
  ExperienceStemboxRoute: ExperienceStemboxRoute,
  ThoughtsEarlyWorksRoute: ThoughtsEarlyWorksRoute,
  ThoughtsLearningToTakeUpSpaceRoute: ThoughtsLearningToTakeUpSpaceRoute,
  ThoughtsMagicInTheMundaneRoute: ThoughtsMagicInTheMundaneRoute,
  WorkFarmAppRoute: WorkFarmAppRoute,
  WorkLidarRoute: WorkLidarRoute,
  WorkPulseRoute: WorkPulseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
