/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkPulseRouteImport } from './routes/work_.pulse'
import { Route as ExperienceLightmatterRouteImport } from './routes/experience_.lightmatter'
import { Route as ExperiencePMARouteImport } from './routes/experience_.pma'
import { Route as ThoughtsEarlyWorksRouteImport } from './routes/thoughts_.early-works'
import { Route as ThoughtsLearningToTakeUpSpaceRouteImport } from './routes/thoughts_.learning-to-take-up-space'
import { Route as ThoughtsMagicInTheMundaneRouteImport } from './routes/thoughts_.magic-in-the-mundane'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPulseRoute = WorkPulseRouteImport.update({
  id: '/work_/pulse',
  path: '/work/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceLightmatterRoute = ExperienceLightmatterRouteImport.update({
  id: '/experience_/lightmatter',
  path: '/experience/lightmatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencePMARoute = ExperiencePMARouteImport.update({
  id: '/experience_/pma',
  path: '/experience/pma',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsEarlyWorksRoute = ThoughtsEarlyWorksRouteImport.update({
  id: '/thoughts_/early-works',
  path: '/thoughts/early-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsLearningToTakeUpSpaceRoute = ThoughtsLearningToTakeUpSpaceRouteImport.update({
  id: '/thoughts_/learning-to-take-up-space',
  path: '/thoughts/learning-to-take-up-space',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsMagicInTheMundaneRoute = ThoughtsMagicInTheMundaneRouteImport.update({
  id: '/thoughts_/magic-in-the-mundane',
  path: '/thoughts/magic-in-the-mundane',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/work/pulse': typeof WorkPulseRoute
  '/experience/lightmatter': typeof ExperienceLightmatterRoute
  '/experience/pma': typeof ExperiencePMARoute
  '/thoughts/early-works': typeof ThoughtsEarlyWorksRoute
  '/thoughts/learning-to-take-up-space': typeof ThoughtsLearningToTakeUpSpaceRoute
  '/thoughts/magic-in-the-mundane': typeof ThoughtsMagicInTheMundaneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/work/pulse': typeof WorkPulseRoute
  '/experience/lightmatter': typeof ExperienceLightmatterRoute
  '/experience/pma': typeof ExperiencePMARoute
  '/thoughts/early-works': typeof ThoughtsEarlyWorksRoute
  '/thoughts/learning-to-take-up-space': typeof ThoughtsLearningToTakeUpSpaceRoute
  '/thoughts/magic-in-the-mundane': typeof ThoughtsMagicInTheMundaneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRoute
  '/work_/pulse': typeof WorkPulseRoute
  '/experience_/lightmatter': typeof ExperienceLightmatterRoute
  '/experience_/pma': typeof ExperiencePMARoute
  '/thoughts_/early-works': typeof ThoughtsEarlyWorksRoute
  '/thoughts_/learning-to-take-up-space': typeof ThoughtsLearningToTakeUpSpaceRoute
  '/thoughts_/magic-in-the-mundane': typeof ThoughtsMagicInTheMundaneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience' | '/thoughts' | '/work' | '/work/pulse' | '/experience/lightmatter' | '/experience/pma' | '/thoughts/early-works' | '/thoughts/learning-to-take-up-space' | '/thoughts/magic-in-the-mundane'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experience' | '/thoughts' | '/work' | '/work/pulse' | '/experience/lightmatter' | '/experience/pma' | '/thoughts/early-works' | '/thoughts/learning-to-take-up-space' | '/thoughts/magic-in-the-mundane'
  id: '__root__' | '/' | '/experience' | '/thoughts' | '/work' | '/work_/pulse' | '/experience_/lightmatter' | '/experience_/pma' | '/thoughts_/early-works' | '/thoughts_/learning-to-take-up-space' | '/thoughts_/magic-in-the-mundane'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceRoute: typeof ExperienceRoute
  ThoughtsRoute: typeof ThoughtsRoute
  WorkRoute: typeof WorkRoute
  WorkPulseRoute: typeof WorkPulseRoute
  ExperienceLightmatterRoute: typeof ExperienceLightmatterRoute
  ExperiencePMARoute: typeof ExperiencePMARoute
  ThoughtsEarlyWorksRoute: typeof ThoughtsEarlyWorksRoute
  ThoughtsLearningToTakeUpSpaceRoute: typeof ThoughtsLearningToTakeUpSpaceRoute
  ThoughtsMagicInTheMundaneRoute: typeof ThoughtsMagicInTheMundaneRoute
}


declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/pulse': {
      id: '/work_/pulse'
      path: '/work/pulse'
      fullPath: '/work/pulse'
      preLoaderRoute: typeof WorkPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience_/lightmatter': {
      id: '/experience_/lightmatter'
      path: '/experience/lightmatter'
      fullPath: '/experience/lightmatter'
      preLoaderRoute: typeof ExperienceLightmatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience_/pma': {
      id: '/experience_/pma'
      path: '/experience/pma'
      fullPath: '/experience/pma'
      preLoaderRoute: typeof ExperiencePMARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/early-works': {
      id: '/thoughts_/early-works'
      path: '/thoughts/early-works'
      fullPath: '/thoughts/early-works'
      preLoaderRoute: typeof ThoughtsEarlyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/learning-to-take-up-space': {
      id: '/thoughts_/learning-to-take-up-space'
      path: '/thoughts/learning-to-take-up-space'
      fullPath: '/thoughts/learning-to-take-up-space'
      preLoaderRoute: typeof ThoughtsLearningToTakeUpSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/magic-in-the-mundane': {
      id: '/thoughts_/magic-in-the-mundane'
      path: '/thoughts/magic-in-the-mundane'
      fullPath: '/thoughts/magic-in-the-mundane'
      preLoaderRoute: typeof ThoughtsMagicInTheMundaneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceRoute: ExperienceRoute,
  ThoughtsRoute: ThoughtsRoute,
  WorkRoute: WorkRoute,
  WorkPulseRoute: WorkPulseRoute,
  ExperienceLightmatterRoute: ExperienceLightmatterRoute,
  ExperiencePMARoute: ExperiencePMARoute,
  ThoughtsEarlyWorksRoute: ThoughtsEarlyWorksRoute,
  ThoughtsLearningToTakeUpSpaceRoute: ThoughtsLearningToTakeUpSpaceRoute,
  ThoughtsMagicInTheMundaneRoute: ThoughtsMagicInTheMundaneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
